-- migrate:up
-- =============================================================================
-- Serious Shift — initial Postgres schema
-- Ported 1:1 from the live SQLite schema (serious-shift.db) so the one-off ETL
-- in packages/db/etl/sqlite_to_postgres.py can copy rows while preserving IDs.
--
-- Type mapping:
--   SQLite INTEGER PRIMARY KEY  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT lets the ETL insert existing ids; sequences are bumped after)
--   SQLite REAL                 -> DOUBLE PRECISION
--   SQLite TIMESTAMP/CURRENT_TIMESTAMP -> TIMESTAMPTZ DEFAULT now()
--   SQLite BOOLEAN DEFAULT 1    -> BOOLEAN DEFAULT TRUE
--   CHECK(... IN (...))         -> kept verbatim (double-quoted SQL string
--     literals rewritten to single quotes, which Postgres requires)
-- Tables are ordered so every FK target exists before it is referenced.
-- =============================================================================

-- ── Core entities ───────────────────────────────────────────────────────────

CREATE TABLE thinkers (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     TEXT UNIQUE NOT NULL,
    affiliation              TEXT,
    domain                   TEXT,
    agi_timeline             TEXT,
    economic_worldview       TEXT,
    consumer_behavior_stance TEXT,
    importance_score         INTEGER CHECK (importance_score BETWEEN 1 AND 10),
    signal_quality           TEXT CHECK (signal_quality IN ('high','mixed','noisy')),
    credibility_score        DOUBLE PRECISION DEFAULT 50.0,
    prediction_accuracy      DOUBLE PRECISION,
    outlier_factor           DOUBLE PRECISION,
    bio                      TEXT,
    created_at               TIMESTAMPTZ DEFAULT now(),
    updated_at               TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE sources (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_id           BIGINT REFERENCES thinkers(id),
    title                TEXT NOT NULL,
    date_published       DATE,
    source_type          TEXT CHECK (source_type IN ('article','video','podcast','tweet_thread','paper','talk','essay','interview','book','blog_post','social_media','policy_paper')),
    platform             TEXT,
    url                  TEXT,
    summary              TEXT,
    full_text            TEXT,
    consumer_implication TEXT,
    signal_strength      TEXT CHECK (signal_strength IN ('noise','background','signal','strong_signal')),
    novelty              TEXT CHECK (novelty IN ('new_thinking','repeating_position','position_shift')),
    keynote_impact       TEXT CHECK (keynote_impact IN ('new_slide','strengthens_existing','contradicts_current','obsoletes_section','background')),
    confidence           TEXT CHECK (confidence IN ('speculation','informed_prediction','data_backed')),
    filename             TEXT,
    created_at           TIMESTAMPTZ DEFAULT now(),
    source_depth         INTEGER
);

CREATE TABLE claims (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            BIGINT REFERENCES sources(id),
    thinker_id           BIGINT REFERENCES thinkers(id),
    claim_text           TEXT NOT NULL,
    claim_type           TEXT CHECK (claim_type IN ('prediction','analysis','opinion','fact','recommendation')),
    domain               TEXT CHECK (domain IN ('agi_timeline','labor','consumer_behavior','technology_capability','economy','regulation','existential_risk','enterprise','education','geopolitics')),
    consumer_implication TEXT,
    signal_strength      TEXT CHECK (signal_strength IN ('noise','background','signal','strong_signal')),
    specificity          INTEGER CHECK (specificity BETWEEN 1 AND 5),
    quote                TEXT,
    created_at           TIMESTAMPTZ DEFAULT now(),
    claim_weight         DOUBLE PRECISION,
    duplicate_of         BIGINT REFERENCES claims(id),
    freshness_score      DOUBLE PRECISION
);

CREATE TABLE predictions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id       TEXT UNIQUE NOT NULL,
    claim_id            BIGINT REFERENCES claims(id),
    thinker_id          BIGINT REFERENCES thinkers(id),
    source_id           BIGINT REFERENCES sources(id),
    claim_text          TEXT NOT NULL,
    timeframe           TEXT,
    domain              TEXT,
    specificity         INTEGER CHECK (specificity BETWEEN 1 AND 5),
    falsifiable         BOOLEAN DEFAULT TRUE,
    status              TEXT CHECK (status IN ('pending','partially_true','true','false','expired')) DEFAULT 'pending',
    consensus_alignment DOUBLE PRECISION CHECK (consensus_alignment BETWEEN 0.0 AND 1.0),
    evaluation_date     DATE,
    evaluation_notes    TEXT,
    created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE concepts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT UNIQUE NOT NULL,
    description        TEXT,
    consumer_relevance TEXT,
    keynote_relevance  TEXT CHECK (keynote_relevance IN ('high','medium','low')),
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tensions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT UNIQUE NOT NULL,
    description           TEXT,
    side_a                TEXT,
    side_b                TEXT,
    consumer_implications TEXT,
    current_balance       TEXT,
    keynote_relevance     TEXT CHECK (keynote_relevance IN ('high','medium','low')),
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ DEFAULT now()
);

-- ── Tagging & junctions over core entities ───────────────────────────────────

CREATE TABLE tags (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag TEXT UNIQUE NOT NULL
);

CREATE TABLE claim_concepts (
    claim_id   BIGINT REFERENCES claims(id),
    concept_id BIGINT REFERENCES concepts(id),
    PRIMARY KEY (claim_id, concept_id)
);

CREATE TABLE claim_tensions (
    claim_id   BIGINT REFERENCES claims(id),
    tension_id BIGINT REFERENCES tensions(id),
    side       TEXT CHECK (side IN ('A','B','nuanced')),
    PRIMARY KEY (claim_id, tension_id)
);

CREATE TABLE concept_thinkers (
    concept_id BIGINT REFERENCES concepts(id),
    thinker_id BIGINT REFERENCES thinkers(id),
    stance     TEXT,
    PRIMARY KEY (concept_id, thinker_id)
);

CREATE TABLE tension_thinkers (
    tension_id BIGINT REFERENCES tensions(id),
    thinker_id BIGINT REFERENCES thinkers(id),
    side       TEXT CHECK (side IN ('A','B','nuanced')),
    stance     TEXT,
    PRIMARY KEY (tension_id, thinker_id)
);

CREATE TABLE thinker_disagreements (
    thinker_a_id BIGINT REFERENCES thinkers(id),
    thinker_b_id BIGINT REFERENCES thinkers(id),
    topic        TEXT,
    description  TEXT,
    PRIMARY KEY (thinker_a_id, thinker_b_id, topic)
);

CREATE TABLE source_tags (
    source_id BIGINT REFERENCES sources(id),
    tag_id    BIGINT REFERENCES tags(id),
    PRIMARY KEY (source_id, tag_id)
);

CREATE TABLE claim_tags (
    claim_id BIGINT REFERENCES claims(id),
    tag_id   BIGINT REFERENCES tags(id),
    PRIMARY KEY (claim_id, tag_id)
);

-- ── Keynote ──────────────────────────────────────────────────────────────────

CREATE TABLE keynote_sections (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_title   TEXT NOT NULL,
    section_order   INTEGER,
    current_version INTEGER DEFAULT 1,
    content         TEXT,
    updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE section_claims (
    section_id BIGINT REFERENCES keynote_sections(id),
    claim_id   BIGINT REFERENCES claims(id),
    relevance  TEXT CHECK (relevance IN ('primary','supporting','contrarian')),
    PRIMARY KEY (section_id, claim_id)
);

-- ── Scraper state ────────────────────────────────────────────────────────────

CREATE TABLE source_state (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_id      BIGINT NOT NULL REFERENCES thinkers(id),
    platform        TEXT NOT NULL,
    source_url      TEXT NOT NULL,
    last_fetched_at TIMESTAMPTZ,
    last_item_date  DATE,
    last_run_status TEXT CHECK (last_run_status IN ('ok','partial','failed')),
    items_last_run  INTEGER DEFAULT 0,
    UNIQUE (thinker_id, platform, source_url)
);

-- ── Legacy v1 map structures (kept for parity; superseded by domain_* below) ──

CREATE TABLE sub_trends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    kt_number   INTEGER NOT NULL,
    sort_order  INTEGER NOT NULL,
    domains     TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE sub_trend_claims (
    sub_trend_id BIGINT REFERENCES sub_trends(id),
    claim_id     BIGINT REFERENCES claims(id),
    PRIMARY KEY (sub_trend_id, claim_id)
);

CREATE TABLE macro_scenarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    horizon     TEXT,
    region      TEXT DEFAULT 'Global',
    sort_order  INTEGER NOT NULL,
    domains     TEXT,
    proponents  TEXT,
    skeptics    TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE macro_key_links (
    macro_id         BIGINT REFERENCES macro_scenarios(id),
    key_trend_number INTEGER NOT NULL,
    PRIMARY KEY (macro_id, key_trend_number)
);

CREATE TABLE key_trend_meta (
    kt_number  INTEGER PRIMARY KEY,
    domains    TEXT,
    proponents TEXT,
    skeptics   TEXT,
    velocity   TEXT
);

CREATE TABLE synthesis_insights (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    macro_id    BIGINT REFERENCES macro_scenarios(id),
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE synthesis_insight_claims (
    insight_id BIGINT REFERENCES synthesis_insights(id),
    claim_id   BIGINT REFERENCES claims(id),
    PRIMARY KEY (insight_id, claim_id)
);

CREATE TABLE scenario_links (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  TEXT NOT NULL,
    source_id    BIGINT NOT NULL,
    target_type  TEXT NOT NULL,
    target_id    BIGINT NOT NULL,
    relationship TEXT NOT NULL,
    strength     DOUBLE PRECISION NOT NULL,
    reasoning    TEXT,
    UNIQUE (source_type, source_id, target_type, target_id)
);

-- ── Domain-first v2 map hierarchy (canonical) ────────────────────────────────

CREATE TABLE domains_v2 (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    label             TEXT NOT NULL,
    short_description TEXT NOT NULL,
    description       TEXT NOT NULL,
    sort_order        INTEGER NOT NULL
);

CREATE TABLE domain_scenarios (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         TEXT UNIQUE NOT NULL,
    domain_id    TEXT NOT NULL REFERENCES domains_v2(id),
    name         TEXT NOT NULL,
    description  TEXT NOT NULL,
    horizon      TEXT,
    plausibility TEXT,
    sort_order   INTEGER NOT NULL,
    proponents   TEXT,
    skeptics     TEXT,
    created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_key_trends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    scenario_id BIGINT NOT NULL REFERENCES domain_scenarios(id),
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    subtitle    TEXT NOT NULL,
    velocity    TEXT,
    sort_order  INTEGER NOT NULL,
    proponents  TEXT,
    skeptics    TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_sub_trends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    kt_id       BIGINT NOT NULL REFERENCES domain_key_trends(id),
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    sort_order  INTEGER NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_sub_trend_claims (
    sub_trend_id BIGINT REFERENCES domain_sub_trends(id),
    claim_id     BIGINT REFERENCES claims(id),
    PRIMARY KEY (sub_trend_id, claim_id)
);

CREATE TABLE domain_synthesis_insights (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_synthesis_insight_claims (
    insight_id BIGINT REFERENCES domain_synthesis_insights(id),
    claim_id   BIGINT REFERENCES claims(id),
    PRIMARY KEY (insight_id, claim_id)
);

CREATE TABLE domain_links (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  TEXT NOT NULL,
    source_id    TEXT NOT NULL,
    target_type  TEXT NOT NULL,
    target_id    TEXT NOT NULL,
    relationship TEXT NOT NULL,
    strength     DOUBLE PRECISION NOT NULL,
    reasoning    TEXT,
    UNIQUE (source_type, source_id, target_type, target_id)
);

CREATE TABLE domain_flows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   TEXT NOT NULL REFERENCES domains_v2(id),
    target_id   TEXT NOT NULL REFERENCES domains_v2(id),
    strength    TEXT NOT NULL,
    description TEXT,
    UNIQUE (source_id, target_id)
);

-- ── Indexes (ported from SQLite) ─────────────────────────────────────────────

CREATE INDEX idx_sources_thinker     ON sources(thinker_id);
CREATE INDEX idx_sources_date        ON sources(date_published);
CREATE INDEX idx_claims_source       ON claims(source_id);
CREATE INDEX idx_claims_thinker      ON claims(thinker_id);
CREATE INDEX idx_claims_domain       ON claims(domain);
CREATE INDEX idx_claims_strength     ON claims(signal_strength);
CREATE INDEX idx_claims_type         ON claims(claim_type);
CREATE INDEX idx_predictions_thinker   ON predictions(thinker_id);
CREATE INDEX idx_predictions_status    ON predictions(status);
CREATE INDEX idx_predictions_eval_date ON predictions(evaluation_date);
CREATE INDEX idx_predictions_domain    ON predictions(domain);

-- Common API read paths add a couple of indexes SQLite lacked:
CREATE INDEX idx_claims_duplicate_of ON claims(duplicate_of);
CREATE INDEX idx_claims_weight       ON claims(claim_weight DESC NULLS LAST);

-- migrate:down
DROP TABLE IF EXISTS domain_flows;
DROP TABLE IF EXISTS domain_links;
DROP TABLE IF EXISTS domain_synthesis_insight_claims;
DROP TABLE IF EXISTS domain_synthesis_insights;
DROP TABLE IF EXISTS domain_sub_trend_claims;
DROP TABLE IF EXISTS domain_sub_trends;
DROP TABLE IF EXISTS domain_key_trends;
DROP TABLE IF EXISTS domain_scenarios;
DROP TABLE IF EXISTS domains_v2;
DROP TABLE IF EXISTS scenario_links;
DROP TABLE IF EXISTS synthesis_insight_claims;
DROP TABLE IF EXISTS synthesis_insights;
DROP TABLE IF EXISTS key_trend_meta;
DROP TABLE IF EXISTS macro_key_links;
DROP TABLE IF EXISTS macro_scenarios;
DROP TABLE IF EXISTS sub_trend_claims;
DROP TABLE IF EXISTS sub_trends;
DROP TABLE IF EXISTS source_state;
DROP TABLE IF EXISTS section_claims;
DROP TABLE IF EXISTS keynote_sections;
DROP TABLE IF EXISTS claim_tags;
DROP TABLE IF EXISTS source_tags;
DROP TABLE IF EXISTS thinker_disagreements;
DROP TABLE IF EXISTS tension_thinkers;
DROP TABLE IF EXISTS concept_thinkers;
DROP TABLE IF EXISTS claim_tensions;
DROP TABLE IF EXISTS claim_concepts;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS tensions;
DROP TABLE IF EXISTS concepts;
DROP TABLE IF EXISTS predictions;
DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS thinkers;
