-- migrate:up
-- Content Logic (June 2026) Phase 2: collapse the scenario layer.
-- Key Trends now attach directly to a domain (domain → key_trend → sub_trend → claim);
-- the intermediate domain_scenarios layer is removed. domain_links rows that pointed
-- at scenarios used a TEXT ref (e.g. 'scn:1') with no FK, so they are cleared too.
DELETE FROM domain_links
 WHERE source_type = 'scn' OR target_type = 'scn'
    OR source_id LIKE 'scn:%' OR target_id LIKE 'scn:%';
ALTER TABLE domain_key_trends DROP COLUMN scenario_id;
DROP TABLE domain_scenarios;

-- migrate:down
CREATE TABLE domain_scenarios (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         TEXT UNIQUE NOT NULL,
    domain_id    TEXT NOT NULL REFERENCES domains_v2(id),
    name         TEXT NOT NULL,
    description  TEXT NOT NULL,
    horizon      TEXT,
    plausibility TEXT,
    sort_order   INTEGER NOT NULL,
    proponents   TEXT,
    skeptics     TEXT,
    created_at   TIMESTAMPTZ DEFAULT now()
);
-- Re-added nullable: the original NOT NULL value cannot be reconstructed once dropped.
ALTER TABLE domain_key_trends ADD COLUMN scenario_id BIGINT REFERENCES domain_scenarios(id);
